spring:
  jpa:
    show-sql: true

  datasource:
    url: 'jdbc:postgresql://localhost:5432/nomis_sync?sslmode=prefer'
    username: postgres
    password: postgres

hmpps-auth:
  url: ${HMPPS_AUTH_URL:http://localhost:8090/auth}
